<a href="https://colab.research.google.com/github/fasthill/ML-DL-study-alone/blob/main/5-1%20%EA%B2%B0%EC%A0%95%20%ED%8A%B8%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import datetime
import os, re

In [2]:
directory_for_predict = '../data/data_for_ml/predict/'
pkl_directory = '../data/company_pkl/'
 
pkl_name= 'sec_historical.pkl'
df= pd.read_pickle(pkl_directory + pkl_name)

In [11]:
df.head(10)

        date   open   high    low  close close_cr       vol
0 2021-12-27  80600  80600  79800  80200    -0.37  10783368
1 2021-12-28  80200  80400  79700  80300     0.12  18226325
2 2021-12-29  80200  80200  78500  78800    -1.87  19794795
3 2021-12-30  78900  79500  78100  78300    -0.63  14236700
4 2022-01-03  79400  79800  78200  78600     0.38  13502112
5 2022-01-04  78800  79200  78300  78700     0.13  12427416
6 2022-01-05  78800  79000  76400  77400    -1.65  25470640
7 2022-01-06  76700  77600  76600  76900    -0.65  12931954
8 2022-01-07  78100  78400  77400  78300     1.82  15163757
9 2022-01-10  78100  78100  77100  78000    -0.38   9947422

In [ ]:
def highlight_rows(row, row_index):
#     is_max = pd.Series(data=False, index=row.index)
#     is_max[column] = s.loc[column] >= threshold
    return ['background-color: yellow' if row in row_index else '' for row in row.index]

In [ ]:
def highlight_greaterthan(s, threshold, column):
    is_max = pd.Series(data=False, index=s.index)
    is_max[column] = s.loc[column] >= threshold
    return ['background-color: yellow' if is_max.any() else '' for _ in is_max]


df.style.apply(highlight_greaterthan, threshold=1.0, column=['C', 'B'], axis=1)

In [40]:
row_index =  [3, 7, 12]

In [41]:
xin = [list(df.index).index(x) for x in row_index]

In [42]:
xin

[3, 7, 12]

In [ ]:
df_one.style.apply(lambda x: ['background-color: yellow' if row in xin else '' for row in range(len(df_one.index))], axis=0)

In [43]:
df.style.apply(lambda x: ['background-color: yellow' if row in xin else '' for row in df.index], axis=0)

In [33]:
def highlight_rows(row, row_index):
    return ['background-color: yellow' if row in [1, 3, 8, 9] else '' for row in row.index]

In [21]:
yes = 'background-color: green'
no = 'background-color: orange'
df.style.apply(lambda L: [ yes if i< 10 else no for i in L ], axis=0)

AttributeError: 'Index' object has no attribute 'style'

In [ ]:
df.tail()

In [24]:
def highlight(x):
    c1 = 'background-color: yellow'
    c2 = 'background-color: blue'

    df1 = pd.DataFrame('', index=x.index, columns=x.columns)
    df1.loc[[5,  7], :] = c1
    df1.loc[[3, 10], :] = c2
    return df1

df.T.style.apply(highlight, axis=None)

KeyError: "None of [Index([5, 7], dtype='int32')] are in the [index]"

In [25]:
df1 = pd.DataFrame('', index=df.index, columns=df.columns)

In [26]:
df1

    date open high low close close_cr vol
0
1
2
3
4
..   ...  ...  ...  ..   ...      ...  ..
346
347
348
349
350

[351 rows x 7 columns]

In [27]:
df1.loc[[5,  7], :]

  date open high low close close_cr vol
5
7

In [ ]:
# file creation timestamp in float
m_time = os.path.getmtime(pkl_directory + pkl_name)
# convert creation timestamp into DateTime object
dt_m = datetime.datetime.fromtimestamp(m_time)

In [16]:
df.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       341, 342, 343, 344, 345, 346, 347, 348, 349, 350],
      dtype='int32', length=351)

In [ ]:
dt_m.hour

In [ ]:
dt_m.minute

In [ ]:
m_time

In [ ]:
a = None

In [ ]:
a

In [ ]:
b = 10

In [ ]:
l = [a, b]

In [ ]:
l

In [ ]:
l[0] == None

In [ ]:
dk = datetime.datetime.today()
dk

In [ ]:
du = dk + datetime.timedelta(hours=-13)
du

In [ ]:
directory_for_predict = './data/data_for_ml/predict/'
pkl_directory = './data/company_pkl/'
pkl_name= 'sec_historical.pkl'
df_historical_temp = pd.read_pickle(pkl_directory + pkl_name)

In [ ]:
import csv
import numpy as np

ndict=[{'name':'Andrew','rollno.':1,'marks':19},
       {'name':'John','rollno.':2,'marks':18},
       {'name':'Roger','rollno.':3,'marks':16}]



ndict = {
    'boosting_type' : ['gbdt', 'dart', ],# ['gbdt', 'dart', 'goss'],
    'learning_rate': (0.0001, 0.004, 'log-uniform'),
    'num_leaves': (3, 15),      
    'max_depth': (0, 50), #[-1], #(0, 50),
    'min_child_samples': (5, 40),
#     'min_child_weight': (0, 5), # 값을 변동시 같은 값이 최적값으로 선정되더라고 precision이 틀림. 반드시 값을 바꾸면서 진행해야 함.
    'max_bin': (100, 1200), # 사용시 0.75%로 올라감 default: 255
#     'max_cat_threshold' : (1, 100),
    'subsample': (0.005, 1.0, 'uniform'), # == bagging_fraction
#     'subsample_freq': (1, 10), # mobis에서 적용시 값이 많이 올라감. default:0
    'colsample_bytree': (0.005, 1.0, 'uniform'),
    'subsample_for_bin': (100000, 1000000),
    'scale_pos_weight': np.arange(0.2, 2, 0.1) ,
    'n_estimators': (700, 12000),
#     'reg_alpha' : (0, 4.0, 'uniform'), # =='lambda_l1': [0, 5], # default 0
#     'reg_lambda' : (0, 4.0, 'uniform'), # == lambda_l2': [0, 5], #default 0    
    'reg_alpha' : np.arange(0, 3, 0.1),
    'reg_lambda' : np.arange(0, 3, 0.1),
    'force_col_wise': ['true'], 
    'boost_from_average' : [True, False],
    'objective': ['binary'],
    'metric': ['binary_logloss'],
}

#define fields
fields=['rollno.','name','marks'] # == fileds=ndict[0].keys()
fields=ndict.keys()
values = ndict.values()

with open('dictnew.csv',mode='w') as file:
    writer=csv.DictWriter(file,fieldnames=fields)#create writer object
    writer.writeheader() #writing field names(headings)
    writer.writerows(ndict) #writing the data

In [2]:
ndict = {
    'boosting_type' : ['gbdt', 'dart', ],# ['gbdt', 'dart', 'goss'],
    'learning_rate': (0.0001, 0.004, 'log-uniform'),
    'num_leaves': (3, 15),      
    'max_depth': (0, 50), #[-1], #(0, 50),
    'min_child_samples': (5, 40),
#     'min_child_weight': (0, 5), # 값을 변동시 같은 값이 최적값으로 선정되더라고 precision이 틀림. 반드시 값을 바꾸면서 진행해야 함.
    'max_bin': (100, 1200), # 사용시 0.75%로 올라감 default: 255
#     'max_cat_threshold' : (1, 100),
    'subsample': (0.005, 1.0, 'uniform'), # == bagging_fraction
#     'subsample_freq': (1, 10), # mobis에서 적용시 값이 많이 올라감. default:0
    'colsample_bytree': (0.005, 1.0, 'uniform'),
    'subsample_for_bin': (100000, 1000000),
    'scale_pos_weight': np.arange(0.2, 2, 0.1) ,
    'n_estimators': (700, 12000),
#     'reg_alpha' : (0, 4.0, 'uniform'), # =='lambda_l1': [0, 5], # default 0
#     'reg_lambda' : (0, 4.0, 'uniform'), # == lambda_l2': [0, 5], #default 0    
    'reg_alpha' : np.arange(0, 3, 0.1),
    'reg_lambda' : np.arange(0, 3, 0.1),
    'force_col_wise': ['true'], 
    'boost_from_average' : [True, False],
    'objective': ['binary'],
    'metric': ['binary_logloss'],
}
fields=ndict.keys()
values = ndict.values()
pd.DataFrame([fields, values], index=['parameter','value']).T.to_csv("dictt.csv")

In [ ]:
values = ndict[0].values()

In [ ]:
values

In [1]:
ndict = {
    'boosting_type' : ['gbdt', 'dart', ],# ['gbdt', 'dart', 'goss'],
    'learning_rate': (0.0001, 0.004, 'log-uniform'),}
ndict2 = {
        'boost_from_average' : [True, False],
    'objective': ['binary'],
    'metric': ['binary_logloss'],
}

In [2]:
ndict, ndict2

({'boosting_type': ['gbdt', 'dart'],
  'learning_rate': (0.0001, 0.004, 'log-uniform')},
 {'boost_from_average': [True, False],
  'objective': ['binary'],
  'metric': ['binary_logloss']})

In [3]:
ndict+ndict2

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [4]:
from collections import Counter

x = {'both1':1, 'both2':2, 'only_x': 100 }
y = {'both1':10, 'both2': 20, 'only_y':200 }

z = dict(Counter(x)+Counter(y))

In [5]:
z

{'both1': 11, 'both2': 22, 'only_x': 100, 'only_y': 200}

In [27]:
dsum = {}

In [28]:
dsumk = list(ndict.keys()) + list(ndict2.keys())

In [29]:
dsumv = list(ndict.values()) + list(ndict2.values())

In [32]:
for i in range(len(ndict)+len(ndict2)):
    print(i)
    dsum[dsumk[i]] = dsumv[i]

0
1
2
3
4

In [43]:
def add_dict(dict1, dict2):
    dsum = {}
    d_k = list(dict1.keys()) + list(dict2.keys())  # sum keys list
    d_v = list(dict1.values()) + list(dict2.values())  # sum values list
    for i in range(len(d_k)):
        dsum[d_k[i]] = d_v[i]
    return dsum

In [45]:
dsum = add_dict(ndict2, ndict)
dsum

{'boost_from_average': [True, False],
 'objective': ['binary'],
 'metric': ['binary_logloss'],
 'boosting_type': ['gbdt', 'dart'],
 'learning_rate': (0.0001, 0.004, 'log-uniform')}

In [33]:
dsum

{'boosting_type': ['gbdt', 'dart'],
 'learning_rate': (0.0001, 0.004, 'log-uniform'),
 'boost_from_average': [True, False],
 'objective': ['binary'],
 'metric': ['binary_logloss']}

In [7]:
dica.app = [ndict+ndict2]
dica

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'